// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCV5Fm2lN5tK69iREM6LV0YOeBtE1Z5so4',
    appId: '1:708987822724:web:df840f2f4cebcb8eb598d1',
    messagingSenderId: '708987822724',
    projectId: 'broker-17325',
    authDomain: 'broker-17325.firebaseapp.com',
    storageBucket: 'broker-17325.firebasestorage.app',
    measurementId: 'G-VL8Y6DJ7BT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAb10kHiAkF0cImfR0MP0PBPtGgkUPlfCg',
    appId: '1:708987822724:android:4de9fa1fbb50e60cb598d1',
    messagingSenderId: '708987822724',
    projectId: 'broker-17325',
    storageBucket: 'broker-17325.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXyj6cz_e_KQtp322mu8WvEyecyxcpiC0',
    appId: '1:708987822724:ios:fdf833919392d4c9b598d1',
    messagingSenderId: '708987822724',
    projectId: 'broker-17325',
    storageBucket: 'broker-17325.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXyj6cz_e_KQtp322mu8WvEyecyxcpiC0',
    appId: '1:708987822724:ios:fdf833919392d4c9b598d1',
    messagingSenderId: '708987822724',
    projectId: 'broker-17325',
    storageBucket: 'broker-17325.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCV5Fm2lN5tK69iREM6LV0YOeBtE1Z5so4',
    appId: '1:708987822724:web:f6cba473e5365d15b598d1',
    messagingSenderId: '708987822724',
    projectId: 'broker-17325',
    authDomain: 'broker-17325.firebaseapp.com',
    storageBucket: 'broker-17325.firebasestorage.app',
    measurementId: 'G-9R2FCZTKQJ',
  );
}
